// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB25BnPEuldDx3kXWBJKvHFIf9gd9P4H8A',
    appId: '1:916212979017:web:3348292583401ed595b698',
    messagingSenderId: '916212979017',
    projectId: 'flutter-login-app-1d24c',
    authDomain: 'flutter-login-app-1d24c.firebaseapp.com',
    storageBucket: 'flutter-login-app-1d24c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCwlvpPvMqhVq3gt488_wJY1Cf5tFUgsg',
    appId: '1:916212979017:android:cddfc0d7902496c895b698',
    messagingSenderId: '916212979017',
    projectId: 'flutter-login-app-1d24c',
    storageBucket: 'flutter-login-app-1d24c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCW21lLTgFd5pmAuxmKetN4g1lLOWuTlA8',
    appId: '1:916212979017:ios:8d2979b93f8016cb95b698',
    messagingSenderId: '916212979017',
    projectId: 'flutter-login-app-1d24c',
    storageBucket: 'flutter-login-app-1d24c.appspot.com',
    iosBundleId: 'com.example.myLoginApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCW21lLTgFd5pmAuxmKetN4g1lLOWuTlA8',
    appId: '1:916212979017:ios:3b39d1b97b5329e795b698',
    messagingSenderId: '916212979017',
    projectId: 'flutter-login-app-1d24c',
    storageBucket: 'flutter-login-app-1d24c.appspot.com',
    iosBundleId: 'com.example.myLoginApp.RunnerTests',
  );
}
